contact_links:
  - name: Get technical support
    url: https://ubcode.useblocks.com/_static/contact.html
    about: Get technical support
  - name: Request a license
    url: https://ubcode.useblocks.com/_static/contact.html
    about: Request a license
